### ISSUE TITLE
Dependency piface not compatible with latest release node  

### ISSUE THREAD

**Issue by thierry13790** [LeJeko/homebridge-garage-piface#2]
Thank you for the delivery ! Dependency package PIFACE does not compile with latest Jnode package release 12. So it’s impossible to install package homebridge-garage-piface. Else you have any other idea’s ? 

Once trying to install it with another package compatible with node v12 called piface-node-12 I was able to install. But it was needed some modifications ! It will be welcome to have compatibility with node 12 inside this repo !

**Comment by LeJeko** [comment]
Thank you for identifying this problem. I modified the dependency which corrects the problem during the installation.
I made this plug-in for a friend and I no longer have PiFace to check if there is no side effect.
Can you please check?

**Comment by thierry13790** [comment]
Thank you i qualified it and it works !

**Comment by LeJeko** [comment]
Thank you. Feel free to send PR if you can improve!
