### ISSUE TITLE
No status partial open 

### ISSUE THREAD

**Issue by thierry13790** [LeJeko/homebridge-garage-piface#3]
Everything works fine once Garage gate is open or closed, good detection of status open or close.  But if it’s partially open after being closed it is considered close inside HomeKit. The problem ! But I’ve 2 sensors which are able To detect status, they are not taken into account in this case. To get garage partially open I stop the opening by click on close button because this is the only way I can stop it to be partially open. I’ve only one button to open or close garage inside my  remote (Step by step mode). First click garage gate go in a way, then second click it go in reverse mode. Any idea’s of the problem ?

**Comment by thierry13790** [comment]
Problem solved by modification inside index.json the configuration of input was not taken from configuration file I will share fix soon

**Comment by thierry13790** [comment]
I closed the ticket but forgot to provide solution, that's why i reopen it.

This is the solution to solve the problem : 

Inside index.js :

Replace :

this.closedDoorSensorValue = config.closedSensorValue || 1
this.openDoorSensorValue = config.openSensorValue || 1

By : 

this.closedDoorSensorValue = config.closedSensorValue
this.openDoorSensorValue = config.openSensorValue

Thus value found in config file is taken into account even if value is zero. It avoid value 0 to be transformed in 1 

Please @LeJeko can you update ? i qualified it on my side

**Comment by LeJeko** [comment]
Thank you for the fix @thierry13790.
Updated in version 1.0.1.
